" Generated by vim-plug
" Wed Jul 29 10:16:15 2026
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['coc.nvim'].commit = '2ebe9d4e950e7599cab417cdfa17d5df1fb28a40'
silent! let g:plugs['copilot.vim'].commit = 'a12fd5672110c8aa7e3c8419e28c96943ca179be'
silent! let g:plugs['fzf'].commit = 'd39595ae66e2835561f6caf2b9478e887a269362'
silent! let g:plugs['fzf.vim'].commit = 'd2a59a992a2455f609c0fde2ebd84427ea8f919a'
silent! let g:plugs['lightline.vim'].commit = 'd042c506cb2e7a59112a72447e0b5fe8739d9d1d'
silent! let g:plugs['nerdtree'].commit = '690d061b591525890f1471c6675bcb5bdc8cdff9'
silent! let g:plugs['vim-commentary'].commit = '64a654ef4a20db1727938338310209b6a63f60c9'
silent! let g:plugs['vim-fugitive'].commit = '3b753cf8c6a4dcde6edee8827d464ba9b8c4a6f0'
silent! let g:plugs['vim-gitgutter'].commit = '90b75207bd9b55d8ac4af15f72b4e935462014d0'
silent! let g:plugs['vim-repeat'].commit = '65846025c15494983dafe5e3b46c8f88ab2e9635'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-templates'].commit = 'c4ce1903fc458688bc421f0cb4572af8a8977cdb'

PlugUpdate!
